### ISSUE TITLE
Bricklayer  (multiple blog columns) is not working in EI and Edge

### ISSUE THREAD

**Issue by polachp** [hibbitts-design/grav-skeleton-open-publishing-space#10]
Hello,
The column design (bricklayer) for mainblog posts page is not working for IE or Edge, while in Chrome its working.

Easilly replicated by opening the page http://demo.hibbittsdesign.org/grav-open-publishing-quark/ in those brosers.
The original quark theme works well.

![Výstřižek](https://user-images.githubusercontent.com/1156411/106126992-5e30ab00-615e-11eb-8b81-704ca285f250.JPG)
![Výstřižek edge](https://user-images.githubusercontent.com/1156411/106127119-83251e00-615e-11eb-8919-5391ac4c33dc.JPG)

**Comment by paulhibbitts** [comment]
Thanks for reporting this issue @polachp , but I cannot seem to replicate it on Mac or Windows Edge:

<img width="1440" alt="2021-01-28_07-39-15" src="https://user-images.githubusercontent.com/1812771/106161514-f23d4b00-613b-11eb-9425-aa6db26f4689.png">

Could you please try to clear your Browser cache or perhaps try it on another computer with Edge?

Thanks very much,
Paul

**Comment by polachp** [comment]
I tested it on virtual machine with updated browsers and it works.
Sadly on machine I replicated this, I have a very strange version with some old Edge  44.18362.1.0. But after updating even on this machine it works.

Sorry for the false alarm!

**Comment by paulhibbitts** [comment]
No problem at all, I am glad everything is working ok again!
