### ISSUE TITLE
Req: Blog with 3 columns and sidebar

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-skeleton-open-publishing-space#11]
Is it possible to have a grid layout with 3 columns and (optionally) a sidebar?
Unfortunately changing the grid size of the theme to 'Large' or 'Medium' does not add an extra column.

**Comment by paulhibbitts** [comment]
Hi @awrog , if it is possible with Quark (the parent theme) it should be possible with OPS... I do not think it is however, but still take a look and please let me know what you find.

**Comment by awrog** [comment]
Hi Paul, that looks surprisingly easy!
[This post](https://discourse.getgrav.org/t/3-column-content-on-blog-page-with-quark-theme/7128) set me on the right track.
It seems the proper CSS-definition is already in place, but needs to be uncommented.
Just edit: `\user\themes\quark\css\bricklayer.css`
Uncomment the following and you're done. You can adapt min-width: 1200px to you liking
```
/*@media screen and (min-width: 1200px) {*/
    /*.bricklayer-column-sizer {*/
        /*width: 33.33333%;*/
    /*}*/
/*}*/
```
It would be a great adition to be activated by default, my min-width is 1440

**Comment by paulhibbitts** [comment]
Hi @awrog , I am really pleased to see you found a great way to display 3 columns! At this point I'd be wary of changing the default display of the theme for other existing users but if anyone else contacts me with this request I will share the info you found. Thanks very much.

**Comment by awrog** [comment]
Hi Paul,

You could mention it in the readme file.

Regards

**Comment by paulhibbitts** [comment]
That's a great idea @awrog , I've updated the Quark Open Publishing theme ReadMe as you suggest:
https://github.com/hibbitts-design/grav-theme-quark-open-publishing/blob/master/README.md#further-customization

Thanks again!
