### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by MaluNoPeleke** [hibbitts-design/grav-skeleton-open-publishing-space#12]
I have installed 1.6.7 clean and then updated to Grav 1.7.9 without a problem but when also updating the plugins I got the following error message:

`[2021-03-23 21:24:25] grav.CRITICAL: Template "partials/noscript.html.twig" is not defined in "partials/base-root.html.twig" at line 55. - Trace: #0 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Service/OutputServiceProvider.php(36): Grav\Common\Twig\Twig->processSite('html') #1 /var/www/virtual/peleke7/html/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #2 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/RenderProcessor.php(39): Pimple\Container->offsetGet('output') #3 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #4 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #5 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #6 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #7 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #8 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/PagesProcessor.php(81): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #9 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #10 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #11 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #13 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #16 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #19 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #22 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #25 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /var/www/virtual/peleke7/html/grav/user/plugins/admin/classes/plugin/Router.php(51): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #28 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/RequestProcessor.php(63): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #31 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #34 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #37 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #40 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #41 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #42 /var/www/virtual/peleke7/html/grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /var/www/virtual/peleke7/html/grav/system/src/Grav/Common/Grav.php(295): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /var/www/virtual/peleke7/html/grav/index.php(58): Grav\Common\Grav->process() #45 {main} [] []`

How to fix it?

**Comment by paulhibbitts** [comment]
Hi @MaluNoPeleke , I've not seen this issue yet myself and am not sure it is specific to my skeleton. A quick search found this one logged related issue:
https://github.com/getgrav/grav/issues/3260

Is a reinstall feasible in your case?

**Comment by MaluNoPeleke** [comment]
I just reinstalled and updated again, same error after updating the following ten plugins:

> Admin Panel, from v1.10.1 to v1.10.8
> Email, from v3.1.0 to v3.1.1
> External Links, from v1.6.2 to v1.6.3
> Flex Objects, from v1.0.1 to v1.0.5
> Form, from v4.3.0 to v5.0.1
> Login, from v3.3.8 to v3.4.1
> Page Inject, from v1.4.3 to v1.4.4
> Related Pages, from v1.2.2 to v1.2.3
> Shortcode Core, from v5.0.3 to v5.0.5
> TNT Search, from v3.3.0 to v3.3.1

Can you reproduce it?

**Comment by paulhibbitts** [comment]
Is this from an older version of Open Publishing Space? I cannot reproduce it. Perhaps change to the standard "Quark" theme and then try to update? Then after that update change back to Quark Open Publishing?

Let me know how things go.
Paul

**Comment by MaluNoPeleke** [comment]
I just downloaded the Skeleton in version 1.6.7 from https://getgrav.org/downloads/skeletons

**Comment by paulhibbitts** [comment]
Thanks @MaluNoPeleke , but the thing I do no understand is that Skeleton was just released this weekend so right now it already has Grav 1.7.9 installed. I just downloaded it myself with no errors and verified it has Grav 1.7.9 installed. Might there be something happening with your download process/copy?

**Comment by MaluNoPeleke** [comment]
Yes, you are right, don't know why it downloaded a version from January.
