### ISSUE TITLE
Removal plugin customadmin

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-skeleton-open-publishing-space#13]
Since the developer of the plugin customadmin has archived the [customadmin-repository](https://github.com/RomainFallet/grav-plugin-customadmin), wouldn't it be wise to omit this pluging from the open-publishing-space skeleton, to avoid future incompatibility?

**Comment by paulhibbitts** [comment]
Sorry for the delay in noticing this issue @awrog , I will need to explore this further as I do not have a replacement and so far no issues have shown up in my on-going release testing etc
