### ISSUE TITLE
Workflow wasn't generating admin versions. 

### ISSUE THREAD

**Issue by bnnk** [hibbitts-design/grav-skeleton-open-publishing-space#14]
Hi, I am BK Shrinandhan. When I was trying to download your theme, I saw that the workflow didn't have a skeleton+Admin nor on the Skeletons page. So I manually re-ran and I have tagged it as v1.6.9.

**Comment by paulhibbitts** [comment]
Hi @bnnk , I am not sure what you mean as I just checked and the Admin is in the skeleton download - do you mean the theme or skeleton?

**Comment by paulhibbitts** [comment]
Thanks for the PR, if if I recall I do not use this option as I include the Admin Panel in the default build, and do not create a second build with the Admin. It's been a while I set this up though, so I will keep an eye out for this issue next release. I just checked the most recent Skeleton release on GetGrav.org and it does have the Admin Panel.

FYI, the approach I took to include the Admin Panel in the default ZIP file build was to use the `.dependencies` file route:
https://github.com/hibbitts-design/grav-skeleton-open-publishing-space/blob/master/.dependencies
https://getgrav.org/blog/skeletons-build-automation

**Comment by bnnk** [comment]
@paulhibbitts  I see the pull request closed. Is it that we don't want to take the changes and it stays the same way ?. Just want to know for my clarification..

**Comment by paulhibbitts** [comment]
Hi @bnnk, that is correct as with my default build the Admin Panel is included already. Download your test build https://github.com/bnnk/grav-skeleton-open-publishing-space/releases/download/v1.6.9/grav-skeleton-open-publishing-space.zip and you will see this once the ZIP is expanded (look in the Plugins folder).
