### ISSUE TITLE
On http://learn.hibbittsdesign.org/openpublishingspace

### ISSUE THREAD

**Issue by HelifeWasTaken** [hibbitts-design/grav-skeleton-open-publishing-space#16]
You are running PHP 7.2.34, but Grav needs at least PHP 7.3.6 to run.

**Comment by paulhibbitts** [comment]
Hi @Heliferepo , thanks for the heads-up something went awry with the PHP update for the server. Thanks again! https://learn.hibbittsdesign.org/
