### ISSUE TITLE
Twitter Feed not loading

### ISSUE THREAD

**Issue by B1gG** [hibbitts-design/grav-skeleton-open-publishing-space#2]
Hi Guys,
I have my page on bigg.dynu.net but my twitter feed is not loading the feeds.
My config is:
```
title: 'Twitter Feed'
twitter_feed_text: 'Tweets by @minutesoftech'
twitter_feed_url: 'https://twitter.com/minutesoftech'
twitter_feed_height: 600
published: true
visible: false
```
any idea where to check?

**Comment by paulhibbitts** [comment]
That looks right... perhaps try that in the Open Publishing Skeleton?

Here is the Twitter Feed page from that too:
```
---
title: 'Twitter Feed'
twitter_feed_text: 'Tweets by @hibbittsdesign'
twitter_feed_url: 'https://twitter.com/hibbittsdesign'
twitter_feed_height: 600
published: true
visible: false
---

#### Twitter
```

Let me know how things go.

**Comment by B1gG** [comment]
Hi Paul,
thanks for your quick response.
I actually tried replacing my config with yours and I still not seeing the feeds.
Anything else I can try? Only appears the link to twitter but not the actual feed.

**Comment by paulhibbitts** [comment]
Hmmm... maybe clear the cache or try a force-refresh in the Browser? Also, is this online or a local test?

**Comment by B1gG** [comment]
Hooo thanks for the hint ...
I have the tracking protection in my browser, once deactivated is working, I can see your twitter feeds :)
Thanks

**Comment by paulhibbitts** [comment]
Awesome, glad you got it going!
