### ISSUE TITLE
Setting page other than blog page as home page

### ISSUE THREAD

**Issue by krismyu** [hibbitts-design/grav-skeleton-open-publishing-space#4]
Hi, thank you so much for developing this theme/skeleton! I was wondering if there is a way to set the blog page to *not* be the homepage (.  I tried to rename the directory 01.blog/ to 11.blog, but that still leaves the homepage as the blog page. This strategy does work with the https://github.com/getgrav/grav-skeleton-blog-site skeleton, e.g., I renamed 01.blog to 02.blog and then created a 01.home and then that new home page I created showed up as the homepage.  I'm sorry if I missing something totally obvious---I'm a newbie. I took a look in the config files, but nothing changed when I tried to put '/blog' in blog:route: in user/config/site.yaml, and in user/pages/11.blog/blog.md, I have blog_url set as the default /blog.  Thank you!

**Comment by paulhibbitts** [comment]
Hi @krismyu , thanks for your interest in the theme/skeleton!

Yes, you should be able to set another page as the homepage - what you describe looks very close.

I would set the numeric prefix of the page to be homepage `01.` and then renumber the actual Blog page to something suitable. Then, in the Admin Panel go to Config -> System and choose your new Homepage in the `Home page` menu dropdown.

Please let me know if the above works for you.

**Comment by krismyu** [comment]
Thanks so much Paul! I didn't think to look in `system.yaml`, but now I see that there's indeed the section to change the homepage.  Works great!  Thank you again for your work on this skeleton/theme and your quick and helpful response!  I didn't know about h5p before I looked at your work and it looks really cool as a teaching tool, so thank you for introducing me to that, too!

```yaml
home:
  alias: /blog
  hide_in_urls: false
```
