### ISSUE TITLE
Compactibility chrome, edge, ie

### ISSUE THREAD

**Issue by ghost** [hibbitts-design/grav-skeleton-open-publishing-space#5]
https://gdsign.fr/ftp/galerie/chrome.png     Yes ok
https://gdsign.fr/ftp/galerie/edge.png         Partial not ok
https://gdsign.fr/ftp/galerie/ie.png              ie = trash ignored

With ur demo same problem.

hello,
Its possible to fix that ? i have just installed default pack master no modification.

thanks u for this job.

**Comment by paulhibbitts** [comment]
Hi @FranckySnowFsX , could you please test the parent theme of Open Publishing Space (Quark - https://github.com/getgrav/grav-theme-quark) and let me know if you see the same issues? I do know that Quark is not very compatible with IE and also has some issues with Edge.

**Comment by ghost** [comment]
Hey @paulhibbitts its ok with quark, this theme fix problem. For ie not really a problem i think some many people use Firefox chrome or edge now.

Thanks for ur support and nice joob.
