### ISSUE TITLE
Date-picker does not seem to work

### ISSUE THREAD

**Issue by awrog** [hibbitts-design/grav-skeleton-open-publishing-space#6]
Latest version of this skeleton.
It looks like the date-picker is not responding...

![datepicker](https://user-images.githubusercontent.com/12153667/50903267-9bae2880-141d-11e9-8512-0f6b4a4a74b4.gif)

**Comment by paulhibbitts** [comment]
Hi @awrog , this looks like a known issue in the Admin that is scheduled for an update: https://github.com/getgrav/grav-plugin-admin/issues/1581
