### ISSUE TITLE
missing a slash ?

### ISSUE THREAD

**Issue by JOduMonT** [hibbitts-design/grav-skeleton-open-publishing-space#8]
when I download https://getgrav.org/download/skeletons/open-publishing-space-site/1.6.3
than unzip it I have this error
````
0 - SplFileInfo::isFile(): open_basedir restriction in effect. File(/home/user/web/domain.tld/public_htmluser/plugins/customadmin/customadmin.css) is not within the allowed path(s): ...
````
in some how I believe the issue is a missing slash before `user/plugins/customadmin/customadmin.css` but I can't find it your code so I can't PR it

**Comment by paulhibbitts** [comment]
Hi @JOduMonT , could you share a few more details like OS and when exactly this happens? I just downloaded and unzipped and did not come across anything. Thanks very much.

**Comment by JOduMonT** [comment]
it was with HestiaCP on Ubuntu 18.04
I made my nginx template from wordpress by copying the nginx webserver profile
maybe I missed a slash (i did'nt doubt about it before :P)
